#:kivy 2.0.0

<Game>:
    canvas.before:
        Color:
            rgb: .1, .1, .1
        Rectangle:
            pos: self.pos
            size: self.size
    AnchorLayout:
        anchor_x: "center"
        anchor_y: "center"
        Label:
            text_size: (500, None)
            font_size: 30
            size: self.texture_size
            halign: "center"
            text: "Connecté.\nMembres : " + root.membersStr
