#:kivy 2.0.0

<Home>:
    anchor_x: "center"
    anchor_y: "center"
    canvas.before:
        Color:
            rgb: .2, .2, .2
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        id: form
        orientation: "vertical"
        size_hint: (.4, .8)
        padding: (mm(3), mm(5.5))
        canvas.before:
            Color:
                rgb: tbarColor
            RoundedRectangle:
                pos: self.pos
                size: self.size